//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace LD55.Inputs
{
    public partial class @Controls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""88c77359-c9da-4711-9148-5a02f6c3a6c9"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e861a287-7d34-4dba-b8d0-b36fc74da93b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Summon"",
                    ""type"": ""Button"",
                    ""id"": ""bf04132c-253b-4e63-a28e-eddc223b3fbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonA"",
                    ""type"": ""Button"",
                    ""id"": ""ca81d098-656c-48ee-bd42-3505d2af10b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonB"",
                    ""type"": ""Button"",
                    ""id"": ""9b70da6f-0847-49d1-880a-31aa4eaef3e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonC"",
                    ""type"": ""Button"",
                    ""id"": ""2b61d353-fab7-414c-9527-d836f60cf175"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonD"",
                    ""type"": ""Button"",
                    ""id"": ""b226f0c5-dd0c-405e-b76d-22efe1c51d6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonE"",
                    ""type"": ""Button"",
                    ""id"": ""291d6244-b5ff-4c8a-8560-61d12e6139e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonF"",
                    ""type"": ""Button"",
                    ""id"": ""cde8123c-ba02-41b2-ab03-6f6b192924b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonG"",
                    ""type"": ""Button"",
                    ""id"": ""cb2403ce-1a43-420f-9f11-e63ed83ac312"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonH"",
                    ""type"": ""Button"",
                    ""id"": ""13a3f289-59f2-41d8-93cb-bb892e53a6fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonPageNext"",
                    ""type"": ""Button"",
                    ""id"": ""9ae8e2f0-c178-45f9-b6e0-57549f7e7729"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SummonPagePrevious"",
                    ""type"": ""Button"",
                    ""id"": ""c2a05982-962f-4a69-89a4-9b32920f9336"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""564968c1-79b0-406c-b1f0-bd01e5bad81a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""87fd708c-ede2-4b28-bf16-b2bdab80a408"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5e8d64ac-ee08-4fcb-82bc-ff9667b5a965"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9b351df7-3f15-4d11-a71d-eeadb2b9a407"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""051213d8-f918-411b-a861-7716764f4b57"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""50c6d1f5-2f2d-452f-8923-b90463178db0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c983f438-b5bc-4b5f-acb4-f0117312896e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a65bf36-7a71-458a-ab24-9183c52779fa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Summon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a34d7a6-df90-4c25-8933-6d961db9ee33"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Summon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""220321e5-1ace-42d1-87de-513185dd021a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a52475a5-6825-44ee-b010-94d7bd9502f5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7983d65-f8d9-49e3-8325-39966307fa33"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5d1eba1-3ff5-4863-9213-d726b8847136"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2160e2f8-cedf-43fd-8792-b3e34e9a2f41"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db210c0e-e833-44b9-acf0-67fb32dd2825"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12e1cfff-5063-4603-a035-f85ecc33c7b6"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33ac65fe-c6dc-4555-b5ef-652c7c72625c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf6c71bd-77e1-41f9-b3a6-e81cc1e977d4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f558e47c-bc9d-4122-ac64-60f986c6b943"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5c9e86-9875-4cb1-bfdb-5f85e891c2aa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonF"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37d461a0-625c-4bd2-adad-0e9dd3b52a9c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonF"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebb63d7d-fbe7-4fd0-8b23-b408874ac652"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""413835c3-bc7c-434d-83ca-4320dfda6f9f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1772cd27-3971-41fc-81a9-09188bb16b44"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7c60546-bda2-4936-a696-2180454f6b81"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6a8a4b8-d4b2-4c3e-b699-db2d3cb60a93"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonPageNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbe8babc-0273-4b22-8af4-d2384e15cee8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonPageNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6b4d8b0-1a65-4292-b447-333e94a34323"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonPagePrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b60ce388-ca2b-45c7-831f-75c6f4c8541f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SummonPagePrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25f42d83-fe8f-4ee3-bded-bad8e15e467c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f2aa382-d58d-42bf-8f87-bd95659821a2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
            m_Player_Summon = m_Player.FindAction("Summon", throwIfNotFound: true);
            m_Player_SummonA = m_Player.FindAction("SummonA", throwIfNotFound: true);
            m_Player_SummonB = m_Player.FindAction("SummonB", throwIfNotFound: true);
            m_Player_SummonC = m_Player.FindAction("SummonC", throwIfNotFound: true);
            m_Player_SummonD = m_Player.FindAction("SummonD", throwIfNotFound: true);
            m_Player_SummonE = m_Player.FindAction("SummonE", throwIfNotFound: true);
            m_Player_SummonF = m_Player.FindAction("SummonF", throwIfNotFound: true);
            m_Player_SummonG = m_Player.FindAction("SummonG", throwIfNotFound: true);
            m_Player_SummonH = m_Player.FindAction("SummonH", throwIfNotFound: true);
            m_Player_SummonPageNext = m_Player.FindAction("SummonPageNext", throwIfNotFound: true);
            m_Player_SummonPagePrevious = m_Player.FindAction("SummonPagePrevious", throwIfNotFound: true);
            m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_Movement;
        private readonly InputAction m_Player_Summon;
        private readonly InputAction m_Player_SummonA;
        private readonly InputAction m_Player_SummonB;
        private readonly InputAction m_Player_SummonC;
        private readonly InputAction m_Player_SummonD;
        private readonly InputAction m_Player_SummonE;
        private readonly InputAction m_Player_SummonF;
        private readonly InputAction m_Player_SummonG;
        private readonly InputAction m_Player_SummonH;
        private readonly InputAction m_Player_SummonPageNext;
        private readonly InputAction m_Player_SummonPagePrevious;
        private readonly InputAction m_Player_Interact;
        public struct PlayerActions
        {
            private @Controls m_Wrapper;
            public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_Player_Movement;
            public InputAction @Summon => m_Wrapper.m_Player_Summon;
            public InputAction @SummonA => m_Wrapper.m_Player_SummonA;
            public InputAction @SummonB => m_Wrapper.m_Player_SummonB;
            public InputAction @SummonC => m_Wrapper.m_Player_SummonC;
            public InputAction @SummonD => m_Wrapper.m_Player_SummonD;
            public InputAction @SummonE => m_Wrapper.m_Player_SummonE;
            public InputAction @SummonF => m_Wrapper.m_Player_SummonF;
            public InputAction @SummonG => m_Wrapper.m_Player_SummonG;
            public InputAction @SummonH => m_Wrapper.m_Player_SummonH;
            public InputAction @SummonPageNext => m_Wrapper.m_Player_SummonPageNext;
            public InputAction @SummonPagePrevious => m_Wrapper.m_Player_SummonPagePrevious;
            public InputAction @Interact => m_Wrapper.m_Player_Interact;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Summon.started += instance.OnSummon;
                @Summon.performed += instance.OnSummon;
                @Summon.canceled += instance.OnSummon;
                @SummonA.started += instance.OnSummonA;
                @SummonA.performed += instance.OnSummonA;
                @SummonA.canceled += instance.OnSummonA;
                @SummonB.started += instance.OnSummonB;
                @SummonB.performed += instance.OnSummonB;
                @SummonB.canceled += instance.OnSummonB;
                @SummonC.started += instance.OnSummonC;
                @SummonC.performed += instance.OnSummonC;
                @SummonC.canceled += instance.OnSummonC;
                @SummonD.started += instance.OnSummonD;
                @SummonD.performed += instance.OnSummonD;
                @SummonD.canceled += instance.OnSummonD;
                @SummonE.started += instance.OnSummonE;
                @SummonE.performed += instance.OnSummonE;
                @SummonE.canceled += instance.OnSummonE;
                @SummonF.started += instance.OnSummonF;
                @SummonF.performed += instance.OnSummonF;
                @SummonF.canceled += instance.OnSummonF;
                @SummonG.started += instance.OnSummonG;
                @SummonG.performed += instance.OnSummonG;
                @SummonG.canceled += instance.OnSummonG;
                @SummonH.started += instance.OnSummonH;
                @SummonH.performed += instance.OnSummonH;
                @SummonH.canceled += instance.OnSummonH;
                @SummonPageNext.started += instance.OnSummonPageNext;
                @SummonPageNext.performed += instance.OnSummonPageNext;
                @SummonPageNext.canceled += instance.OnSummonPageNext;
                @SummonPagePrevious.started += instance.OnSummonPagePrevious;
                @SummonPagePrevious.performed += instance.OnSummonPagePrevious;
                @SummonPagePrevious.canceled += instance.OnSummonPagePrevious;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }

            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @Movement.started -= instance.OnMovement;
                @Movement.performed -= instance.OnMovement;
                @Movement.canceled -= instance.OnMovement;
                @Summon.started -= instance.OnSummon;
                @Summon.performed -= instance.OnSummon;
                @Summon.canceled -= instance.OnSummon;
                @SummonA.started -= instance.OnSummonA;
                @SummonA.performed -= instance.OnSummonA;
                @SummonA.canceled -= instance.OnSummonA;
                @SummonB.started -= instance.OnSummonB;
                @SummonB.performed -= instance.OnSummonB;
                @SummonB.canceled -= instance.OnSummonB;
                @SummonC.started -= instance.OnSummonC;
                @SummonC.performed -= instance.OnSummonC;
                @SummonC.canceled -= instance.OnSummonC;
                @SummonD.started -= instance.OnSummonD;
                @SummonD.performed -= instance.OnSummonD;
                @SummonD.canceled -= instance.OnSummonD;
                @SummonE.started -= instance.OnSummonE;
                @SummonE.performed -= instance.OnSummonE;
                @SummonE.canceled -= instance.OnSummonE;
                @SummonF.started -= instance.OnSummonF;
                @SummonF.performed -= instance.OnSummonF;
                @SummonF.canceled -= instance.OnSummonF;
                @SummonG.started -= instance.OnSummonG;
                @SummonG.performed -= instance.OnSummonG;
                @SummonG.canceled -= instance.OnSummonG;
                @SummonH.started -= instance.OnSummonH;
                @SummonH.performed -= instance.OnSummonH;
                @SummonH.canceled -= instance.OnSummonH;
                @SummonPageNext.started -= instance.OnSummonPageNext;
                @SummonPageNext.performed -= instance.OnSummonPageNext;
                @SummonPageNext.canceled -= instance.OnSummonPageNext;
                @SummonPagePrevious.started -= instance.OnSummonPagePrevious;
                @SummonPagePrevious.performed -= instance.OnSummonPagePrevious;
                @SummonPagePrevious.canceled -= instance.OnSummonPagePrevious;
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
            }

            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        public interface IPlayerActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnSummon(InputAction.CallbackContext context);
            void OnSummonA(InputAction.CallbackContext context);
            void OnSummonB(InputAction.CallbackContext context);
            void OnSummonC(InputAction.CallbackContext context);
            void OnSummonD(InputAction.CallbackContext context);
            void OnSummonE(InputAction.CallbackContext context);
            void OnSummonF(InputAction.CallbackContext context);
            void OnSummonG(InputAction.CallbackContext context);
            void OnSummonH(InputAction.CallbackContext context);
            void OnSummonPageNext(InputAction.CallbackContext context);
            void OnSummonPagePrevious(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
        }
    }
}
